
const Menu = [
  {
    id: 1,
    image: "images/noodles.jpeg",
    name: "Noodles",
    category: "Breakfast",
    price: "50 ₹",
  },

  {
    id: 2,
    image: "images/pyazpakodi.jpg",
    name: "Pyaz Pakodi",
    category: "Breakfast",
    price: "20 ₹",
  },
  {
    id: 3,
    image: "images/dhokla.jpg",
    name: "Dhokla",
    category: "Breakfast",
    price: "30 ₹",
  },
  {
    id: 4,
    image: "images/poha.jpg",
    name: "Poha",
    category: "Breakfast",
    price: "50 ₹",
  },
  {
    id: 5,
    image: "images/bunmakkhan.jpg",
    name: "Bun Makkhan",
    category: "Breakfast",
    price: "20 ₹",
  },
  {
    id: 6,
    image: "images/plainsandwitch.jpg",
    name: "Plain Sandwitch",
    category: "Breakfast",
    price: "30 ₹",
  },
  {
    id: 7,
    image: "images/vegsandwitch.jpg",
    name: "Fresh Veggies Sandwitch",
    category: "Breakfast",
    price: "60₹",
  },
  {
    id: 8,
    image: "images/brownpoha.jpg",
    name: "Brown Poha",
    category: "Breakfast",
    price: "50 ₹",
  },
  {
    id: 9,
    image: "images/rajmachawal.jpg",
    name: "Rajma Chawal",
    category: "Lunch",
    price: "80 ₹",
  },
  {
    id: 10,
    image: "images/cholebhature.jpg",
    name: "Chole Bhature",
    category: "Lunch",
    price: "80 ₹",
  },
  {
    id: 11,
    image: "images/cholekulche.jpg",
    name: "Chole Kulche",
    category: "Lunch",
    price: "60 ₹",
  },
  {
    id: 12,
    image: "images/paneerparatha.jpg",
    name: "Paneer Paratha",
    category: "Lunch",
    price: "80 ₹",
  },
  {
    id: 13,
    image: "images/alooparatha.jpg",
    name: "Aloo Paratha",
    category: "Lunch",
    price: "60 ₹",
  },
  {
    id: 14,
    image: "images/paneertikka.jpg",
    name: "Paneer Tikka",
    category: "Lunch",
    price: "100 ₹",
  },
  {
    id: 15,
    image: "images/vegman.jpg",
    name: "Veg. Manchurian",
    category: "Lunch",
    price: "80 ₹",
  },
  {
    id: 16,
    image: "images/chillipotato.jpg",
    name: "Chilli Potato",
    category: "Lunch",
    price: "60 ₹",
  },
  {
    id: 17,
    image: "images/plaindaal.jpg",
    name: "Plain Daal",
    category: "Dinner",
    price: "120 ₹",
  },
  {
    id: 18,
    image: "images/daalmakhni.jpg",
    name: "Daal Makhni",
    category: "Dinner",
    price: "150 ₹",
  },
  {
    id: 19,
    image: "images/daaltadka.jpg",
    name: "Daal Tadka",
    category: "Dinner",
    price: "130 ₹",
  },
  {
    id: 20,
    image: "images/jeerrice.jpg",
    name: "Jeera Rice",
    category: "Dinner",
    price: "110 ₹",
  },
  {
    id: 21,
    image: "images/plainrice.jpg",
    name: "Plain Rice",
    category: "Dinner",
    price: "100 ₹",
  },
  {
    id: 22,
    image: "images/tawaroti.jpg",
    name: "Tawa Roti",
    category: "Dinner",
    price: "15 ₹",
  },
  {
    id: 23,
    image: "images/tandoorroti.jpg",
    name: "Tandoor Roti",
    category: "Dinner",
    price: "20 ₹",
  },
  {
    id: 24,
    image: "images/butternan.jpg",
    name: "Butter Naan",
    category: "Dinner",
    price: "25 ₹",
  },
  {
    id: 25,
    image: "images/kadahipaneer.jpg",
    name: "Kadahi Paneer",
    category: "Dinner",
    price: "220 ₹",
  },
  {
    id: 26,
    image: "images/paneerbuttermasala.jpg",
    name: "Paneer Butter Masala",
    category: "Dinner",
    price: "230 ₹",
  },
  {
    id: 27,
    image: "images/shahipaneer.jpg",
    name: "Shahi Paneer",
    category: "Dinner",
    price: "250 ₹",
  },
  {
    id: 28,
    image: "images/mixveg.jpg",
    name: "Mix veg",
    category: "Dinner",
    price: "150 ₹",
  },
 
  {
    id: 29,
    image: "images/masalachaap.jpg",
    name: "Masala Chaap",
    category: "Dinner",
    price: "180 ₹",
  },
 
  {
    id: 30,
    image: "images/malaichaap.jpg",
    name: "Malai Chaap",
    category: "Dinner",
    price: "200 ₹",
  },
 
  {
    id: 31,
    image: "images/acharichaap.jpg",
    name: "Achari Chaap",
    category: "Dinner",
    price: "220 ₹",
  },
 
  {
    id: 32,
    image: "images/matarmashroom.jpg",
    name: "Matar Mashroom",
    category: "Dinner",
    price: "220 ₹",
  },
 
];
// console.table(Menu);

export default Menu;